### ISSUE TITLE
HELP HELP MY DRIVE BROKE

### ISSUE THREAD

**Issue by darkx239** [OpenIndiana/openindiana-welcome#13]
PLEASE HELP I COULDN'T FIND ANY ISSUES SECTION HERE EXCEPT THIS ONE MY SSD BROKE IT WAS WORKING FINE AND IT SAYS CYCLIC REDUNDANCY ERROR WHEN I TRY TO INITIALIZE IT IN WINDOWS PLEASE PLEASE FOR THE LOVE OF GOD HELP ME FIX IT IT COST ME $300 PLEASE PLEASE HELP PLEASE DON'T DELETE THIS ISSUE I NEED HELP I KNOW ITS NOT BROKEN HARDWARE WISE ITS OPENINDIANA

**Comment by jimklimov** [comment]
I am afraid it might be just broken. SSDs have a limited ampunt of writes they sustain; then depending on vendor they kick the bucket, become read only, or ignore the age and just spew errors like this. Maybe some vendor tools or professional services can help read the data, maybe it is lost forever.

Backups are always a must.

Also, not sure how this issue relates to OpenIndiana, sorry.

**Comment by pyhalov** [comment]
Sorry, this is not a topic for issue. Please, consider subscribing to openindiana-discuss mailing list. https://openindiana.org/mailman/listinfo/openindiana-discuss. Sorry to hear this, but this is likely an SSD issue.
