### ISSUE TITLE
openindiana.github.io - The download page: https://www.openindiana.org/download/ is borked

### ISSUE THREAD

**Issue by MartinVonReichenberg** [OpenIndiana/openindiana-welcome#15]
The problems are:

- Links need to be opened in another window in order to be downloaded . . .
- Two ISO files got overwritten and are about 8-40 KB big in size . . .

_Please re-upload the files, this leaves the distribution in an unusable state._

Thanks ;-)

**Comment by Toasterson** [comment]
Thanks for the report. It seems our Wordpress is a bit borked indeed.

**Comment by Toasterson** [comment]
Please use https://dlc.openindiana.org/isos/hipster/latest/ until we get the wordpress sorted out.

**Comment by JMadgwick** [comment]
The URL is now https://www.openindiana.org/downloads/ and is working. I think this can be closed.

**Comment by Toasterson** [comment]
Oh, yep, thats actually a website issue :) and yes it's fixed now with the new website. Closing
